### ISSUE TITLE
Laravel 8 support, config?

### ISSUE THREAD

**Issue by eduardonwa** [Splidejs/splide-extension-video#26]
I noticed that when I:

1. Install the extension through NPM
2. Initialize Splide via the `script` tag
3. Copied and paste the skeleton or default HTML that comes in https://splidejs.com/extension-video/

The plug-in doesn't start. I was able to use the general purpose for the plug-in which are images but somehow I wasn't able to do the same with the extension video. Hoping someone could tell me how to properly set this up in a Laravel 8 application,, thanks. 

`        <script>
            new Splide( '#splide', {
                video: {
                    autoplay: true,
                    mute    : true,
                },
            } );
        </script>
`

Same thing happens if I target the extension using a CDN.

**Comment by NaotoshiFujita** [comment]
Close the issue due to the major version update.
Feel free to create a [new issue](https://github.com/Splidejs/splide-extension-video/issues) or open a [new discussion](https://github.com/Splidejs/splide/discussions).

---

You need to mount the extension.
https://splidejs.com/extensions/video/#installation
